# Cava specific windowrules

windowrule = float on, match:class org.omarchy.cava
windowrule = tag +small-window, match:title cava
windowrule = tag -default-opacity, match:title cava
windowrule = tag -terminal, match:title cava
windowrule = max_size 350 350, match:title cava, match:tag small-window
windowrule = move 600 300, match:class org.omarchy.cava, match:title cava
windowrule = opacity 0.5 0.5, match:title cava
