windowrule = no_screen_share on, match:title ^(Proton Pass Web App - Librewolf)$
windowrule = tag +floating-window, match:class ^(Proton Pass Web App - Librewolf)$

windowrule = no_screen_share on, match:title Proton - LibreWolf
windowrule = tag +floating-window, match:class LibreWolf


